from typing import Any, NoReturn
from simplibs.exception import ValidationError


def raise_invalid_pattern_error(
    node: Any,
    pattern_string: str,
    err: Exception
) -> NoReturn:
    """Raise a ValidationError when re.compile fails to compile the rendered pattern string.

    Args:
        node: The root Regex node being compiled (included for diagnostic context).
        pattern_string: The rendered string representation of the tree.
        err: The original caught re.error exception instance.

    Raises:
        ValidationError: Always.
    """
    node_type = type(node).__name__

    raise ValidationError(
        error_name="INVALID_PATTERN_ERROR",
        label="pattern_string",
        expected="a valid regular expression pattern string",
        value=pattern_string,
        problem=(
            f"The regex pattern generated by {node_type} failed to compile in Python's re engine.",
            f"Rendered pattern string: {pattern_string!r}",
            "See the underlying regex error details displayed below.",
        ),
        how_to_fix=(
            "Inspect the generated pattern string for syntax or structural errors.",
            "Verify group names, quantifier boundaries, and escape sequences in the node tree.",
        ),
        exception=err,
    )


_DESIGN_NOTES = """
# raise_invalid_pattern_error — RegexPattern Compilation Error Wrapper

## Purpose
Wraps native re.error exceptions into structured ValidationError diagnostics,
preserving the original error instance for context without duplicating its output in the text.
"""