import pytest
import re

from simplibs.exception import ValidationError
from simplibs.exception.testing import assert_exception_function
from simplibs.regex.compiler._validations import (
    raise_invalid_pattern_error,
)


@pytest.mark.parametrize(
    "node, pattern_string",
    [
        ("MockNode1", "(unbalanced"),
        ("MockNode2", "*invalid_quantifier"),
        ("MockNode3", "(?P<name"),
    ],
)
def test_raise_invalid_pattern_error_contract(
    subtests,
    node,
    pattern_string,
) -> None:
    """Verify that raise_invalid_pattern_error raises ValidationError
    wrapping the underlying re.error when regex compilation fails."""

    try:
        re.compile(pattern_string)
    except re.error as err:
        original_err = err
    else:
        pytest.fail("Expected re.compile to fail with re.error for test pattern.")

    node_type = type(node).__name__

    assert_exception_function(
        subtests,
        raise_invalid_pattern_error,
        invalid_params=(node, pattern_string, original_err),
        exception_type=ValidationError,
        error_name="INVALID_PATTERN_ERROR",
        label="pattern_string",
        expected="a valid regular expression pattern string",
        value=pattern_string,
        problem=(
            f"The regex pattern generated by {node_type} failed to compile in Python's re engine.",
            f"Rendered pattern string: {pattern_string!r}",
            "See the underlying regex error details displayed below.",
        ),
        how_to_fix=(
            "Inspect the generated pattern string for syntax or structural errors.",
            "Verify group names, quantifier boundaries, and escape sequences in the node tree.",
        ),
        exception=original_err,
        verbose=False,
    )